name: Prompt Evaluator Tests
on:
  pull_request:
    paths:
      - 'prompt-evaluator/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r prompt-evaluator/requirements.txt pytest
      - run: pytest prompt-evaluator/tests
